language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
  - if [ -n "$(gofmt -s -l . | grep -v "vendor")" ]; then diff -u <(echo -n) <(gofmt -d $(gofmt -s -l . | grep -v "vendor")); fi
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - go get github.com/haya14busa/goverage
  - goverage -coverprofile=coverage.txt ./...
  - bash <(curl -s https://codecov.io/bash) -t c5bd3dd8-e037-45d6-a426-968b3462a930

jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - git clone https://github.com/Comcast/comcast-bascule.git
        - cd comcast-bascule
        # build comcast-bascule
